# Assignment 2
For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats

In [97]:
df = pd.read_csv ('assets/NISPUF17.csv')

keep = ["SEQNUMC", "EDUC1", "CBF_01", "P_NUMFLU", "SEX", "P_NUMVRC", "HAD_CPOX"]
df = df[keep]

df["EDUC1x"] = df["EDUC1"].replace({1: "less than high school", 2: "high school", 3: "more than high school but not college",
                          4: "college"})

df["CBF_01x"] = df["CBF_01"].replace({1: "Yes", 2: "No", 77: np.nan,
                          99: np.nan})

df["HAD_CPOXx"] = df["HAD_CPOX"].replace({1: "Yes", 2: "No", 77: np.nan,
                          99: np.nan})

df["SEXx"] = df["SEX"].replace({1: "male", 2: "female"})

df.head(20)

,SEQNUMC,EDUC1,CBF_01,P_NUMFLU,SEX,P_NUMVRC,HAD_CPOX,EDUC1x,CBF_01x,HAD_CPOXx,SEXx
0,128521,4,1,NaN,1,NaN,2,college,Yes,No,male
1,10741,3,2,NaN,1,NaN,2,more than high school but not college,No,No,male
2,220011,3,2,NaN,2,NaN,2,more than high school but not college,No,No,female
3,86131,4,2,3.0,2,1.0,2,college,No,No,female
4,227141,1,1,0.0,2,0.0,2,less than high school,Yes,No,female
5,207941,3,2,NaN,1,NaN,2,more than high school but not college,No,No,male
6,221381,4,1,0.0,2,1.0,2,college,Yes,No,female
7,182861,3,1,0.0,2,0.0,2,more than high school but not college,Yes,No,female
8,161121,2,1,0.0,1,0.0,1,high school,Yes,Yes,male
9,143401,3,1,NaN,1,NaN,2,more than high school but not college,Yes,No,male
10,128211,3,1,3.0,1,1.0,2,more than high school but not college,Yes,No,male
11,92921,4,99,NaN,2,NaN,2,college,NaN,No,female
12,137041,4,1,3.0,1,1.0,2,college,Yes,No,male
13,46531,2,1,NaN,1,NaN,2,high school,Yes,No,male
14,87781,4,1,NaN,1,NaN,2,college,Yes,No,male
15,41081,1,1,NaN,1,NaN,2,less than high school,Yes,No,male
16,188611,1,1,3.0,1,2.0,2,less than high school,Yes,No,male
17,461,3,2,NaN,1,NaN,2,more than high school but not college,No,No,male
18,462,3,2,NaN,1,NaN,2,more than high school but not college,No,No,male
19,136171,4,1,2.0,1,1.0,2,college,Yes,No,male

In [57]:
def proportion_of_education():
    
    # your code goes here
    # YOUR CODE HERE
    
    import pandas as pd
    import numpy as np
    import scipy.stats as stats
    
    df = pd.read_csv ('assets/NISPUF17.csv')

    keep = ["SEQNUMC", "EDUC1", "CBF_01", "P_NUMFLU", "SEX", "P_NUMVRC", "HAD_CPOX"]
    df = df[keep]

    df["EDUC1x"] = df["EDUC1"].replace({1: "less than high school", 2: "high school", 3: "more than high school but not college",
                          4: "college"})

    df["CBF_01x"] = df["CBF_01"].replace({1: "Yes", 2: "No", 77: np.nan,
                          99: np.nan})

    df["HAD_CPOXx"] = df["HAD_CPOX"].replace({1: "Yes", 2: "No", 77: np.nan,
                          99: np.nan})

    df["SEXx"] = df["SEX"].replace({1: "male", 2: "female"})
    
    x = df["EDUC1x"].value_counts()/len(df["EDUC1x"])
    proportion_dict = x.to_dict()
    return proportion_dict
    
    raise NotImplementedError()

In [ ]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."

## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

In [71]:
def average_influenza_doses():
    # YOUR CODE HERE
    
    import pandas as pd
    import numpy as np
    import scipy.stats as stats
    
    df = pd.read_csv ('assets/NISPUF17.csv')

    keep = ["SEQNUMC", "EDUC1", "CBF_01", "P_NUMFLU", "SEX", "P_NUMVRC", "HAD_CPOX"]
    df = df[keep]

    df["EDUC1x"] = df["EDUC1"].replace({1: "less than high school", 2: "high school", 3: "more than high school but not college",
                          4: "college"})

    df["CBF_01x"] = df["CBF_01"].replace({1: "Yes", 2: "No", 77: np.nan,
                          99: np.nan})

    df["HAD_CPOXx"] = df["HAD_CPOX"].replace({1: "Yes", 2: "No", 77: np.nan,
                          99: np.nan})

    df["SEXx"] = df["SEX"].replace({1: "male", 2: "female"})
    
    x = df.groupby("CBF_01x")["P_NUMFLU"].mean()
    return (x["Yes"], x["No"])
    
    raise NotImplementedError()

In [ ]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."

## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

In [156]:
def chickenpox_by_sex():
    # YOUR CODE HERE
    
    import pandas as pd
    import numpy as np
    import scipy.stats as stats
    
    df = pd.read_csv ('assets/NISPUF17.csv')

    keep = ["SEQNUMC", "EDUC1", "CBF_01", "P_NUMFLU", "SEX", "P_NUMVRC", "HAD_CPOX"]
    df = df[keep]

    df["EDUC1x"] = df["EDUC1"].replace({1: "less than high school", 2: "high school", 3: "more than high school but not college",
                          4: "college"})

    df["CBF_01x"] = df["CBF_01"].replace({1: "Yes", 2: "No", 77: np.nan,
                          99: np.nan})

    df["HAD_CPOXx"] = df["HAD_CPOX"].replace({1: "Yes", 2: "No", 77: np.nan,
                          99: np.nan})

    df["SEXx"] = df["SEX"].replace({1: "male", 2: "female"})
    
    df_vax = df[df["P_NUMVRC"]>= 1]
    x = pd.crosstab(df_vax["SEXx"], df_vax["HAD_CPOXx"])
    x["Ratio"] = x["Yes"]/x["No"]
    x = x.drop(columns = ["Yes", "No"])
    ratios = x.to_dict()["Ratio"]
    return ratios
    
    raise NotImplementedError()

In [ ]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."

## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [ ]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # this is just an example dataframe
    df=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),
                   "num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})

    # here is some stub code to actually run the correlation
    corr, pval=stats.pearsonr(df["had_chickenpox_column"],df["num_chickenpox_vaccine_column"])
    
    # just return the correlation
    #return corr

    # YOUR CODE HERE
    
    import pandas as pd
    import numpy as np
    import scipy.stats as stats
    
    df = pd.read_csv ('assets/NISPUF17.csv')

    keep = ["SEQNUMC", "EDUC1", "CBF_01", "P_NUMFLU", "SEX", "P_NUMVRC", "HAD_CPOX"]
    df = df[keep]

    df["HAD_CPOXx"] = df["HAD_CPOX"].replace({1: "Yes", 2: "No", 77: np.nan,
                          99: np.nan})

    df = df[(df["P_NUMVRC"]>=0) & (df["HAD_CPOX"]<=2)]

    corr, pval = stats.pearsonr(df["HAD_CPOX"], df["P_NUMVRC"])
    return corr
    
    raise NotImplementedError()

In [167]:
df=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),
                   "num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})

    
df = pd.read_csv ('assets/NISPUF17.csv')

keep = ["SEQNUMC", "EDUC1", "CBF_01", "P_NUMFLU", "SEX", "P_NUMVRC", "HAD_CPOX"]
df = df[keep]


df = df[(df["P_NUMVRC"]>=0) & (df["HAD_CPOX"]<=2)]
corr, pval = stats.pearsonr(df["HAD_CPOX"], df["P_NUMVRC"])
corr

0.07044873460147986

In [168]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."

NameError: name 'corr_chickenpox' is not defined